### ISSUE TITLE
The link to Django-material in the Alternative Themes section is broken.

### ISSUE THREAD

**Issue by jd-boyd** [originalankur/awesome-django-admin#26]
A working but archived link could be  https://github.com/viewflow/django-material  

There is a note to consider using django-viewflow instead.  If I was choosing a quick resolution, it would be to use the archived github link for now.

**Comment by originalankur** [comment]
@jd-boyd raise a PR please. Will merge.

**Comment by originalankur** [comment]
Merged #27
